### ISSUE TITLE
a, a=>c |- b

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/lazyslate#2]
This should fail but works.

![1679602287](https://user-images.githubusercontent.com/43485956/227341554-1aec0273-3ded-4134-947c-4c63a9b3d4a1.png)

Proof:
https://james-oswald.github.io/lazyslate/?proof=N4Igdg9gJgpgziAXAbVASykgjAGnAQwFsYkQsQ8YAPABwCd440IxSAKNAMwAJ9uBjAJQUQAKwCucAC5c0%2DfDJal8cOOOIiaEJotaJQVJAFYAnCbwBPJACYAzAA4Avo5zpMia3jBESiENZFqekZmPRAAIxEJaVl5XVIuAFFNbTR4%2DRBDRCNbABZLJFyAdixnVxAMQq8fKpAghlVQ5SjJGU45BSa%2DFTUNPC0dLoNC+1sCj1sisrdjao0%2DI0DaBqYlP0i8aLaO9JAe9RJ+1PThxHtcgAZxuymXGcQANjnfEAel4Ma1kA4ecN5hTatWKdL77PogAZpIaZJAmIz2a62WzTCruIrPUhFd4rLp7FoxdpxXFJFKDNanez2K4gKyIXK5IzOAC6eAANmgwABrBAoZD5aws5BGHBFQVPUU4ZC4AVMxxAA

**Comment by Brandon-Rozek** [comment]
Resolved in commit fdd5128
